# Generated by Django 6.0.2 on 2026-06-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_downloadable',
            field=models.BooleanField(default=False),
        ),
    ]
