# Generated by Django 6.0.2 on 2026-06-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_article_is_downloadable'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_download_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_all',
            field=models.BooleanField(default=False),
        ),
    ]
