# Generated by Django 6.0.2 on 2026-07-26 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0004_indicatorsnapshot_trendsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='drive_file_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='articles/'),
        ),
    ]
