# Generated by Django 6.0.2 on 2026-08-05 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0006_category_article_creator_article_creator_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='article',
            name='file',
        ),
        migrations.RemoveField(
            model_name='article',
            name='is_downloadable',
        ),
    ]
