# Generated by Django 6.0.2 on 2026-08-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0007_remove_article_creator_remove_article_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='can_view_all',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
